Repository anno-org/NotesRUs, pull requests merged in 2024-05, with the labels that each got.

#6 Api startup
  Cargo.toml
  src/backend/mod.rs
  src/lib.rs
  src/main.rs
Labels: documentation, enhancement

#16 Created Docker Build Action
  .github/workflows/Push_master.yaml
Labels: enhancement

#12 Dockerfile
  .dockerignore
  Dockerfile
Labels: enhancement

#17 Update Push_master.yaml
  .github/workflows/Push_master.yaml
Labels: bug

#14 readme update
  README.md
  notes_r_us_ui/README.md
Labels: documentation, enhancement

#18 Update Push_master.yaml
  .github/workflows/Push_master.yaml
Labels: bug

#22 Added architectures
  .github/workflows/Push_master.yaml
Labels: enhancement

#25 Fix action
  .github/workflows/Push_master.yaml
Labels: bug

#24 Kubernetes
  Cargo.toml
  README.md
  argocd.yaml
  kubernetes/0-namespace.yaml
  kubernetes/1-cnpg.yaml
  kubernetes/2-cnpg-pooler.yaml
  kubernetes/3-deployment.yaml
  kubernetes/4-service.yaml
  kubernetes/5-ingress.yaml
  kubernetes/README.md
  src/main.rs
Labels: enhancement

#27 Vue alternate
  .dockerignore
  .gitignore
  notes_r_us_ui/Cargo.toml
  notes_r_us_ui/README.md
  notes_r_us_ui/dist/favicon-e9cbd8f50cc65bf2.ico
  notes_r_us_ui/dist/index.html
  notes_r_us_ui/dist/notes_r_us_ui-854551376f2c4157.js
  notes_r_us_ui/dist/notes_r_us_ui-854551376f2c4157_bg.wasm
  notes_r_us_ui/dist/tailwind-b57eb9037ee3b5ea.css
  notes_r_us_ui/end2end/package-lock.json
  notes_r_us_ui/end2end/package.json
  notes_r_us_ui/end2end/playwright.config.ts
  notes_r_us_ui/end2end/tests/example.spec.ts
  notes_r_us_ui/index.html
  notes_r_us_ui/package.json
  notes_r_us_ui/public/favicon.ico
  notes_r_us_ui/public/vite.svg
  notes_r_us_ui/rust-toolchain.toml
  notes_r_us_ui/src/App.vue
  notes_r_us_ui/src/app.rs
  notes_r_us_ui/src/assets/vue.svg
  notes_r_us_ui/src/components/DownloadFile.vue
  notes_r_us_ui/src/components/FileUpload.vue
  notes_r_us_ui/src/components/Sidebar.vue
  notes_r_us_ui/src/main.js
  notes_r_us_ui/src/main.rs
  notes_r_us_ui/src/router.js
  notes_r_us_ui/src/style.css
  notes_r_us_ui/src/views/download.vue
  notes_r_us_ui/src/views/upload.vue
  notes_r_us_ui/tailwind.config.js
  notes_r_us_ui/vite.config.js
Labels: enhancement

#33 fixed comment showing on page, fixed tooltips, animated tooltips
  notes_r_us_ui/public/vite.svg
  notes_r_us_ui/src/assets/vue.svg
  notes_r_us_ui/src/components/Sidebar.vue
Labels: bug, enhancement

#35 aligned icons and tooltips sized better
  notes_r_us_ui/src/components/FileUpload.vue
  notes_r_us_ui/src/components/Sidebar.vue
Labels: bug, enhancement

#36 Docker&action
  .github/workflows/Docker_Build.yaml
  .github/workflows/Push_master.yaml
  Dockerfile
  ci.Dockerfile
Labels: bug, enhancement

#37 Fix Action
  .github/workflows/Docker_Build.yaml
Labels: bug

#38 NPM Command
  .github/workflows/Docker_Build.yaml
Labels: bug

#39 Wrong Dir
  .github/workflows/Docker_Build.yaml
Labels: bug

#42 fixed cors and added frontend origin for local testing
  src/main.rs
Labels: bug, enhancement
