Repository anno-org/NotesRUs, pull requests merged in 2024-08, with the labels that each got.

#87 Internal interface for database
  Cargo.toml
  README.md
  kubernetes/1-service-account.yaml
  kubernetes/2-cnpg-pooler.yaml
  kubernetes/3-hanko-cm.yaml
  kubernetes/4-app-creds.yaml
  kubernetes/5-deployment.yaml
  kubernetes/6-service.yaml
  kubernetes/7-ingress.yaml
  kubernetes/README.md
  migration/Cargo.toml
  migration/README.md
  migration/src/lib.rs
  migration/src/m20220101_000001_users_table.rs
  migration/src/m20240726_065639_clients_table.rs
  migration/src/m20240727_035016_follows_table.rs
  migration/src/m20240727_061854_posts_table.rs
  migration/src/m20240727_063114_comments_table.rs
  migration/src/m20240729_222557_foreign_keys.rs
  migration/src/main.rs
  src/cli.rs
  src/entity/clients.rs
  src/entity/comments.rs
  src/entity/follows.rs
  src/entity/mod.rs
  src/entity/posts.rs
  src/entity/prelude.rs
  src/entity/users.rs
  src/lib.rs
  src/main.rs
Labels: enhancement

#93 Otp codes database addition
  database.dbml
  migration/src/lib.rs
  migration/src/m20240816_001629_otp_codes_table.rs
  src/entity/mod.rs
  src/entity/otp_codes.rs
  src/entity/prelude.rs
  src/entity/users.rs
Labels: enhancement

#94 Improvements To Cargo.Toml
  Cargo.toml
  migration/Cargo.toml
  migration/README.md
Labels: documentation, enhancement

#95 Cargo Update
  Cargo.toml
  migration/Cargo.toml
  migration/src/lib.rs
  migration/src/m20240727_035016_follows_table.rs
  migration/src/m20240727_063114_comments_table.rs
  migration/src/m20240816_001629_otp_codes_table.rs
  migration/src/main.rs
  src/cli.rs
  src/lib.rs
  src/main.rs
Labels: documentation, enhancement

#96 Cargo update
  Cargo.toml
  migration/Cargo.toml
  migration/src/main.rs
  src/main.rs
Labels: bug, documentation

#98 Introjs
  notes_r_us_ui/package.json
  notes_r_us_ui/src/App.vue
  notes_r_us_ui/src/components/BrowseFiles.vue
  notes_r_us_ui/src/components/DownloadFile.vue
  notes_r_us_ui/src/components/FileUpload.vue
  notes_r_us_ui/src/components/introTour.vue
  notes_r_us_ui/src/main.js
Labels: bug, enhancement, User Experience
