Repository anno-org/NotesRUs, pull requests merged in 2024-06, with the labels that each got.

#45 Docker&action
  .github/workflows/Docker_Build.yaml
  README.md
  ci.Dockerfile
Labels: bug

#47 updated images
  kubernetes/3-deployment.yaml
Labels: enhancement

#54 Docker&action
  .github/workflows/Docker_Build.yaml
  ci.Dockerfile
  kubernetes/3-deployment.yaml
Labels: bug, enhancement

#55 Pull Upstream
  .github/workflows/Docker_Build.yaml
  ci.Dockerfile
  kubernetes/3-deployment.yaml
Labels: enhancement

#44 Finished API Routes
  Cargo.toml
  kubernetes/3-deployment.yaml
  notes_r_us_ui/README.md
  src/backend/mod.rs
  src/backend/responses/mod.rs
  src/main.rs
Labels: enhancement

#58 Fix Cors Error
  kubernetes/3-deployment.yaml
  src/main.rs
Labels: bug

#59 Pull Upstream
  .github/workflows/Docker_Build.yaml
  Cargo.toml
  ci.Dockerfile
  kubernetes/3-deployment.yaml
  notes_r_us_ui/README.md
  src/backend/mod.rs
  src/backend/responses/mod.rs
  src/main.rs
Labels: enhancement

#61 Buttons restyling
  notes_r_us_ui/src/components/DeleteFile.vue
  notes_r_us_ui/src/components/DownloadFile.vue
  notes_r_us_ui/src/components/FileUpload.vue
  notes_r_us_ui/src/components/PreviewFile.vue
Labels: enhancement

#62 new parser
  kubernetes/3-deployment.yaml
  notes_r_us_ui/package.json
  notes_r_us_ui/src/App.vue
  notes_r_us_ui/src/components/PreviewFile.vue
Labels: enhancement

#65 Fix filename on download [Frontend]
  notes_r_us_ui/src/components/DownloadFile.vue
  src/main.rs
Labels: bug

#72 Create database.dbml
  database.dbml
Labels: documentation

#73 Remove static routes
  notes_r_us_ui/README.md
  notes_r_us_ui/src/components/BrowseFiles.vue
  notes_r_us_ui/src/components/DeleteFile.vue
  notes_r_us_ui/src/components/DownloadFile.vue
  notes_r_us_ui/src/components/FileUpload.vue
  notes_r_us_ui/src/components/PreviewFile.vue
  notes_r_us_ui/src/router.js
Labels: enhancement

#80 Update 3-deployment.yaml
  kubernetes/3-deployment.yaml
Labels: enhancement

#81 Hanko deployment
  kubernetes/1-service-account.yaml
  kubernetes/3-deployment.yaml
  kubernetes/3-hanko-cm.yaml
  kubernetes/4-app-creds.yaml
  kubernetes/4-service.yaml
  kubernetes/5-deployment.yaml
  kubernetes/5-ingress.yaml
  kubernetes/6-ingress.yaml
  kubernetes/7-service.yaml
  kubernetes/README.md
Labels: enhancement

#82 forgot the silly manifest defintion
  kubernetes/6-ingress.yaml
Labels: bug

#83 apps v1 not app v1
  kubernetes/5-deployment.yaml
Labels: bug

#84 matchlables not matchLables
  kubernetes/5-deployment.yaml
  kubernetes/6-service.yaml
  kubernetes/7-ingress.yaml
Labels: bug
